version: '3.8'

services:
  greenova:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
<<<<<<< HEAD
      - '8000:8000'
=======
      - "8000:8000"
>>>>>>> b3f8326 (release(v0.0.4): comprehensive platform enhancements and new features (#6))
    volumes:
      - greenova:/workspace/greenova
    environment:
      PYTHONUNBUFFERED: 1
<<<<<<< HEAD
    command: ['/bin/bash']

volumes:
  greenova:
=======
    command: ["/bin/bash"]

volumes:
  greenova:
>>>>>>> b3f8326 (release(v0.0.4): comprehensive platform enhancements and new features (#6))
